# Generated by Django 2.2.3 on 2020-11-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
